name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libxcb1-dev libxcb-render-util0-dev libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
